env:
  global:
    - ARCH_TRAVIS_CLEAN_CHROOT=1

language: python
sudo: required

arch:
  packages:
    - yaourt

  script:
    - sudo pacman -Syyu --noconfirm
    - sudo pacman -S --noconfirm python2-pip python2-virtualenv
    - sudo pacman -S --noconfirm ansible

    - echo localhost > inventory
    - sudo ansible-galaxy install --force -r requirements.yml

    # Check syntax
    - sudo ansible-playbook --syntax-check -i inventory test.yml

    # First run
    - sudo ansible-playbook -i inventory test.yml --connection=local --sudo -v

    # Second run Idempotence test
    - >
        sudo ansible-playbook -i inventory test.yml --connection=local --sudo
        | grep -q 'failed=0'
        && (echo 'Idempotence test: pass' && exit 0)
        || (echo 'Idempotence test: fail' && exit 1)

    # Further checks:
    - yaourt --help || exit 1

script:
  - wget https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh
  - chmod 755 arch-travis.sh
  - travis_wait 120 ./arch-travis.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/%
