#!/usr/bin/env ansible-playbook

---
- hosts: all

  pre_tasks:
    - include: tasks/distro_include.yml
    - name: Print
      debug: "msg={{ travis_env }}"
    - name: Print2
      debug: "msg={{ lookup('env', 'TRAVIS') }}"
    - name: Print3
      debug: "msg={{ lookup('env', 'TRAVIS')|default(false, true) }}"

  vars_files:
    - defaults/main.yml

  roles:
    - { role: knopki.sudoers,
        sudoers_filename: "{{ yaourt_makepkg_user }}",
        sudoers_nopasswd: true,
        sudoers: "{{ _sudoers_yaourt_makepkg_user }}"
      }

  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml

