#!/usr/bin/env ansible-playbook

---
- hosts: all

  pre_tasks:
    - name: Print
      debug: "msg={{ travis_env }}"
    - name: Print2
      debug: "msg={{ ansible_distribution }}"
    - include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/{{ travis_env }}.yml"
        - "vars/default.yml"
      when: yaourt_makepkg_user is not defined
    - name: Print3
      debug: "msg={{ default_test_var }}"

  roles:
    - { role: knopki.sudoers,
        sudoers_filename: "{{ yaourt_makepkg_user }}",
        sudoers_nopasswd: true,
        sudoers: "{{ _sudoers_yaourt_makepkg_user }}"
      }

      #    - { role: knopki.sudoers,
      #        sudoers_filename: "travis",
      #        sudoers_nopasswd: true,
      #        sudoers: "{{ _sudoers_yaourt_travis_user }}",
      #        when: is_travis
      #      }

  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml

  vars_files:
    - defaults/main.yml
