---
  vars:
    travis_env: "{{ lookup('env','TRAVIS') }}"
    travis_home: "{{ lookup('env','HOME') }}"

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
      #    - "vars/{{ travis_env }}.yml"
    - "vars/default.yml"
  when: yaourt_makepkg_user is not defined

- include_vars: "vars/travis.yml"
  when: travis_env

- name: travis_env
  debug: "msg={{ travis_env }}"
- name: travis_home
  debug: "msg={{ travis_home }}"
