---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/{{ travis_env }}.yml"
    - "../vars/main.yml"
  when: yaourt_makepkg_user is not defined

- name: Create local packages install user
  user: name={{ yaourt_makepkg_user }} shell=/bin/sh

- name: Copy aur script
  template: src=usr/local/bin/aur.j2 dest=/usr/local/bin/aur mode=755

- name: Update packages database
  pacman: update_cache=yes
  when: yaourt_sync_deps

- name: Install base-devel dependency
  pacman: name=base-devel state=present
  when: yaourt_sync_deps

- name: Install sudo
  pacman: name=sudo state=present
  when: yaourt_sync_deps

- name: Install package-query dependency (yajl)
  pacman:
    name: "{{item }}"
    state: present
  with_items:
    - git
    - yajl

- name: Install yaourt dependency (package-query)
  command: /usr/local/bin/aur package-query
  #when: "'package-query' not in installed_packages.stdout_lines"

- name: Install yaourt
  command: /usr/local/bin/aur yaourt
  #when: "'yaourt' not in installed_packages.stdout_lines"
